### ISSUE TITLE
Minor correction to match

### ISSUE THREAD

**Issue by TacoOblivion** [asterpw/pwevanillaenhance#5]
PWE started using relative protocol links (even though they only use HTTP). In order to fix this to work again I changed the match from this 
`// @match      http://forum.arcgames.com/*`
to
`// @match      htt*://forum.arcgames.com/*`
which didn't really make much sense to me, but it worked so I didn't ask questions.

**Comment by asterpw** [comment]
Fixed in 1.4.0.3
